// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2XMQ8-ifWEXD_yABBtRbqyqQQtwppThA',
    appId: '1:709450181741:web:b634103113cd3d0bfea364',
    messagingSenderId: '709450181741',
    projectId: 'vivatech1-cf6db',
    authDomain: 'vivatech1-cf6db.firebaseapp.com',
    storageBucket: 'vivatech1-cf6db.appspot.com',
    measurementId: 'G-7QVVSJMKRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6HG3Yc4LSeK50aUD_HFTvEbXGzgrRxh0',
    appId: '1:709450181741:android:306d0334c420d7cafea364',
    messagingSenderId: '709450181741',
    projectId: 'vivatech1-cf6db',
    storageBucket: 'vivatech1-cf6db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsw_s0tVfR-GXWz9LUUnoogMLdAgWA664',
    appId: '1:709450181741:ios:b3b2c7f5a4479095fea364',
    messagingSenderId: '709450181741',
    projectId: 'vivatech1-cf6db',
    storageBucket: 'vivatech1-cf6db.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsw_s0tVfR-GXWz9LUUnoogMLdAgWA664',
    appId: '1:709450181741:ios:638e0929ef06eb0ffea364',
    messagingSenderId: '709450181741',
    projectId: 'vivatech1-cf6db',
    storageBucket: 'vivatech1-cf6db.appspot.com',
    iosBundleId: 'com.example.test1.RunnerTests',
  );
}
